# Generated by Django 4.2.4 on 2023-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100, unique=True)),
                ("brand_name", models.CharField(max_length=100)),
                ("country_producer", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("size", models.DecimalField(decimal_places=1, max_digits=1)),
                (
                    "exist_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not available", "Not available"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
            ],
        ),
    ]
